### PR TITLE
don't use PyCrypto library because it's unmaintained + fix MacOS decryption code not removing 16 bytes padding + handle garbage data at end (windows and android) + edit text

### PR DESCRIPTION
**Pull request by xBZZZZ**
read title

### CODE REVIEW

**Comment by naoei** [comment]
Thank you for the contribution, however it would be much better if you were to split this PR into three, each with the changes you've made in the title. I haven't gone and look into the changes yet but I'll wait until you split it into multiple PRs before reviewing.

**Comment by nekitdev** [comment]
I need some confirmation as to if the last 4 bytes are garbage here. We are using `pycryptodome`, which is actively maintained. I'm pretty sure the last 16 bytes are removed, though?

**Comment by xBZZZZ** [comment]
How do I split `don't use PyCrypto library because it's unmaintained + fix MacOS decryption code not removing 16 bytes padding`?

**Comment by naoei** [comment]
First off, please learn how to use Git - more specifically Git Branches. There are plenty of great tutorials online to help you with that.

Once you have learned that, create a branch for each of the changes and PR them as normally (making sure you're selecting the correct branch you want to merge in).

**Comment by xBZZZZ** [comment]
> I'm pretty sure the last 16 bytes are removed, though?

I think that `remove_pad` function doesn't work when `pad` is 16 because 16 is not less than 16.

**Comment by xBZZZZ** [comment]
I don't know how to split `don't use PyCrypto library because it's unmaintained + fix MacOS decryption code not removing 16 bytes padding` because new [MacOS decryption code is completely different than original (link goes to line in files changed tab)](https://github.com/gd-programming/gd.docs/pull/103/files#diff-f90cfcfe3b846aeefa1869914deb017d55c60acc9e4d941b99a12da0f77dd570L81).

This is not `git`'s fault.

**Comment by naoei** [comment]
> I don't know how to split `don't use PyCrypto library because it's unmaintained + fix MacOS decryption code not removing 16 bytes padding` because new MacOS decryption code is completely different than original

That's fine to keep as one PR then.

**Comment by xBZZZZ** [comment]
I splitted this pull request into https://github.com/gd-programming/gd.docs/pull/104, https://github.com/gd-programming/gd.docs/pull/105, https://github.com/gd-programming/gd.docs/pull/106, https://github.com/gd-programming/gd.docs/pull/107.

**Comment by nekitdev** [comment]
> > I'm pretty sure the last 16 bytes are removed, though?
> I think that `remove_pad` function doesn't work when `pad` is 16 because 16 is not less than 16.

`pad` can't be 16 because padding is not added if the size is divisible by 16.

**Comment by xBZZZZ** [comment]
> `pad` can't be 16 because padding is not added if the size is divisible by 16.

Padding <strong>is added</strong> if size is divisible by 16.

here is `CCLocalLevels.dat` from geometry dash for MacOS where padding = 16: https://gdccdated.glitch.me/s/CCLocalLevels_mac16pad.dat

**Comment by nekitdev** [comment]
Yeah, you are correct here. Still, we're not using `cryptography` as it contains much more than we actually need.

**Pull request closed without merging**
