### PR TITLE
Account server endpoints

### PR DESCRIPTION
**Pull request by idkreally-3537**
This adds backupGJAccountNew.php and syncGJAccountNew.php. I also decided to fix the gjp.md issue while I was at it.

### CODE REVIEW

**Comment by Cvolton** [comment]
unlike other endpoints, gameVersion, binaryVersion and gdw are mandatory for backup and sync (or at least some of them i didn't thoroughly check)

**Comment by idkreally-3537** [comment]
Fixed. (I tested the endpoints, gdw is not required for backup and neither is for sync)

**Comment by Wyliemaster** [comment]
Is the content in saveData from your account? Or did you prepare a save just for this?

**Comment by idkreally-3537** [comment]
The save data is from a brand new account, which I haven't done anything on other than beat the first official levels (for the 10 star requirement). The password (GJA_002) is replaced with "0" (the game seems to do this by default, good job robtop :) )

**Pull request merged**
